### ISSUE TITLE
TypeScript errors on generated schema when API being started in prod mode

### ISSUE THREAD

**Issue by chunghha** [nestjs/graphql#638]
## I'm submitting a...

<pre><code>
[x] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

When do "yarn start:prod", I see these TypeScript errors, not all of them listed but some of them here. Errors don't appear on "yarn start" or "yarn start:dev" though.
```
src/graphql.schema.ts:94:32 - error TS2304: Cannot find name '_Any'.

94     _entities(representations: _Any[]): _Entity[] | Promise<_Entity[]>;
                                  ~~~~

src/graphql.schema.ts:94:32 - error TS4075: Parameter 'representations' of method from exported interface has or is using private name '_Any'.

94     _entities(representations: _Any[]): _Entity[] | Promise<_Entity[]>;
                                  ~~~~

src/graphql.schema.ts:94:41 - error TS2304: Cannot find name '_Entity'.

94     _entities(representations: _Any[]): _Entity[] | Promise<_Entity[]>;
                                           ~~~~~~~

src/graphql.schema.ts:94:41 - error TS4057: Return type of method from exported interface has or is using private name '_Entity'.

94     _entities(representations: _Any[]): _Entity[] | Promise<_Entity[]>;
```

The erros are from the private functions of this interface generated.
```
export interface IQuery {
    _entities(representations: _Any[]): _Entity[] | Promise<_Entity[]>;
    _service(): _Service | Promise<_Service>;
    countries(): Country[] | Promise<Country[]>;
    exchangeRate(base: string): Exchange | Promise<Exchange>;
}
```

## Expected behavior

No TypeScript errors.

## Minimal reproduction of the problem with instructions

Use the develop branch of this repo ( https://github.com/chunghha/nest-gql ) to reproduce errors. I included the GraphQLFederationModule with this commit then start to see the private functions are included to the generated graphql.schema.ts.
https://github.com/chunghha/nest-gql/commit/7201832d5f90a577c20869e4ff7939e036181987

"yarn start:prod" to see the errors thrown to console. you may need to install pm2 at global before issuing the command aforementioned.

## What is the motivation / use case for changing the behavior?

I am able to avoid the errors by commenting out the two private functions but I would like to ask if the behavior of including private functions from GraphQL was introduced as NestJS had the feature like as a regression.

## Environment

<pre><code>
Nest version: 6.11.8
"@nestjs/core": "~6.11.8",
"@nestjs/graphql": "~6.6.2"
"typescript": "~3.8.3"

 
For Tooling issues:
- Node version: 12.16.1  
- Platform:  Mac 

Others:

</code></pre>

**Comment by gouroujo** [comment]
I ve fix this by adding the following `global.d.ts` in my project :
```typescript 
declare global {
  type _Service = { sdl: string }
  type _Any     = any
  type _Entity  = any
}
```

**Comment by chunghha** [comment]
Right, that global.d.ts or this interfaces.d.ts fixes the compilation error in my repo. Issue here is, that's a proper way to fix for (or add to) NestJS as well or not, to avoid a custom typings by users of the NestJS module. 
```
type _Service = { sdl: string };
type _Any = any;
type _Entity = any;
```

**Comment by mohammed-shameem** [comment]
I am getting this error in v7. Any workaround on this other than global.d.ts

**Comment by kamilmysliwiec** [comment]
Fixed in 7.2.1.

**Comment by chunghha** [comment]
@kamilmysliwiec, I don't see this issue has been fixed with the 7.2.1. Even I see one more error with NestJS v7/graphql 15.0.0. You may try to reproduce with "yarn start:prod" from the v7 branch of this repo (https://github.com/chunghha/nest-gql) and re-open if you see same.

> $ tsc -p tsconfig.build.json
> node_modules/apollo-link/lib/types.d.ts:23:56 - error TS2315: Type 'ExecutionResult' is not generic.
> 
> 23 }, C = Record<string, any>, E = Record<string, any>> = ExecutionResult<TData> & {
>                                                           ~~~~~~~~~~~~~~~~~~~~~~
> Found 1 error.

**Comment by kamilmysliwiec** [comment]
@chunghha This issue is unrelated and comes from the `apollo-link` library. Let's track this here https://github.com/apollographql/apollo-link/issues/910.

**Comment by chunghha** [comment]
@kamilmysliwiec I know that part with apollo-link. What I wanted to say is that without my interfaces.d.ts I still see the 10 compilation errors with v7.2.1. So, does your fix assume that we need to keep the interfaces.d.ts or global.d.ts?

**Comment by kamilmysliwiec** [comment]
>  So, does your fix assume that we need to keep the interfaces.d.ts or global.d.ts?

No. If you are still having issues, please, paste the console output here

**Comment by chunghha** [comment]
**$ yarn start:prod**
```
yarn run v1.22.4
$ rimraf dist && yarn build
$ tsc -p tsconfig.build.json
node_modules/apollo-link/lib/types.d.ts:23:56 - error TS2315: Type 'ExecutionResult' is not generic.

23 }, C = Record<string, any>, E = Record<string, any>> = ExecutionResult<TData> & {
                                                          ~~~~~~~~~~~~~~~~~~~~~~

src/graphql.schema.ts:94:32 - error TS2304: Cannot find name '_Any'.

94     _entities(representations: _Any[]): _Entity[] | Promise<_Entity[]>;
                                  ~~~~

src/graphql.schema.ts:94:32 - error TS4075: Parameter 'representations' of method from exported interface has or is using private name '_Any'.

94     _entities(representations: _Any[]): _Entity[] | Promise<_Entity[]>;
                                  ~~~~

src/graphql.schema.ts:94:41 - error TS2304: Cannot find name '_Entity'.

94     _entities(representations: _Any[]): _Entity[] | Promise<_Entity[]>;
                                           ~~~~~~~

src/graphql.schema.ts:94:41 - error TS4057: Return type of method from exported interface has or is using private name '_Entity'.

94     _entities(representations: _Any[]): _Entity[] | Promise<_Entity[]>;
                                           ~~~~~~~

src/graphql.schema.ts:94:61 - error TS2304: Cannot find name '_Entity'.

94     _entities(representations: _Any[]): _Entity[] | Promise<_Entity[]>;
                                                               ~~~~~~~

src/graphql.schema.ts:94:61 - error TS4057: Return type of method from exported interface has or is using private name '_Entity'.

94     _entities(representations: _Any[]): _Entity[] | Promise<_Entity[]>;
                                                               ~~~~~~~

src/graphql.schema.ts:95:17 - error TS2304: Cannot find name '_Service'.

95     _service(): _Service | Promise<_Service>;
                   ~~~~~~~~

src/graphql.schema.ts:95:17 - error TS4057: Return type of method from exported interface has or is using private name '_Service'.

95     _service(): _Service | Promise<_Service>;
                   ~~~~~~~~

src/graphql.schema.ts:95:36 - error TS2304: Cannot find name '_Service'.

95     _service(): _Service | Promise<_Service>;
                                      ~~~~~~~~

src/graphql.schema.ts:95:36 - error TS4057: Return type of method from exported interface has or is using private name '_Service'.

95     _service(): _Service | Promise<_Service>;
                                      ~~~~~~~~


Found 11 errors.
```

**Comment by kamilmysliwiec** [comment]
Please, remove `graphql.schema.ts` file and run the application again (after removing `dist` directory and updating `@nestjs/graphql`).

**Comment by chunghha** [comment]
@kamilmysliwiec thanks a lot. That did the trick.
