### ISSUE TITLE
Cannot find module '@apollo/gateway' or its corresponding type declarations.

### ISSUE THREAD

**Issue by piotr-pawlowski** [nestjs/graphql#992]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

There is a problem with dependencies.

```
node_modules/@nestjs/graphql/dist/interfaces/gql-gateway-module-options.interface.d.ts:1:58 - error TS2307: Cannot find module '@apollo/gateway' or its corresponding type declarations.

1 import { GatewayConfig, ServiceEndpointDefinition } from '@apollo/gateway';
                                                           ~~~~~~~~~~~~~~~~~

node_modules/@nestjs/graphql/dist/interfaces/gql-gateway-module-options.interface.d.ts:2:35 - error TS2307: Cannot find module '@apollo/gateway/src/datasources/types' or its corresponding type declarations.

2 import { GraphQLDataSource } from '@apollo/gateway/src/datasources/types';
```

## Environment

<pre><code>
"@nestjs/common": "^7.2.0",
"@nestjs/core": "^7.2.0",
"@nestjs/graphql": "^7.4.5",
"@nestjs/platform-express": "^7.1.2",
"@types/graphql-relay": "^0.6.0",
"apollo-server-express": "^2.15.0",
"graphql": "^15.1.0",
"graphql-tools": "^6.0.10",
</code></pre>

**Comment by razorness** [comment]
I don't understand why it gets not loaded by Yarn. You have to add `@apollo/gateway` explicitly as dev dependency to your project.

**Comment by sgarner** [comment]
Same problem here.

`@apollo/gateway` is not a dependency of [`apollo-server`](https://github.com/apollographql/apollo-server/blob/apollo-server%402.15.0/packages/apollo-server/package.json), [`apollo-server-express`](https://github.com/apollographql/apollo-server/blob/apollo-server-express%402.15.0/packages/apollo-server-express/package.json), or [`apollo-server-core`](https://github.com/apollographql/apollo-server/blob/apollo-server-core%402.15.0/packages/apollo-server-core/package.json), so it's not going to get loaded into our projects automatically.

`@nestjs/graphql` [depends on `@apollo/gateway`](https://github.com/nestjs/graphql/blob/7.4.5/package.json) only as a `devDependency`. I think this is a bug? Since this downstream package actually appears to be required for builds of projects consuming `@nestjs/graphql`, it should be either a `dependency` or `peerDependency`, or the requirement should be eliminated somehow.

**Comment by kamilmysliwiec** [comment]
This issue should be fixed in 7.4.6. Let me know if you still face any errors.

**Comment by piotr-pawlowski** [comment]
@kamilmysliwiec It works properly. Thanks for quick fix!

**Comment by sgarner** [comment]
Thank you @kamilmysliwiec - that's fixed it. :+1:

**Comment by FlxEd** [comment]
Hello, sorry to bother, but it doesn't seems fixed for me in 7.4.6 :/
![image](https://user-images.githubusercontent.com/42470798/85883914-0f92eb00-b7e2-11ea-99c6-57f6bf0b63cb.png)

**Comment by tbrown19** [comment]
Ran into this issue today when checking out code onto a laptop i dont use as often. Fixed by updating Node to latest version.

**Comment by akucharczyk** [comment]
I had the same issue. I had everything up to date, but my node version was v10.x.x. I need to upgrade my local node version to the latest LTS (v12.18.2) and now it works. Maybe it helps someone.

**Comment by esistgut** [comment]
I can confirm the bug with Node 12 LTS on Archlinux.

**Comment by razorness** [comment]
This error is back since `v7.5.2`. `v7.5.1` is last working version.

**Comment by abosaiftaha** [comment]
error solved by updating each of these packages
`@nestjs/common @nestjs/core @nestjs/platform-express` to `7.4.4`

**Comment by htndev** [comment]
> For nvm

I solved my problem by installing node 14.0.0.

**Comment by truonghdpk** [comment]
tha

> > For nvm
> 
> I solved my problem by installing node 14.0.0.

thanks, it works for me

**Comment by ilkaydnc** [comment]
I tried with Node 15.12.0, 14.16.0, and 14.0.0 but I still got the same errors.

This solution solved my errors too

> error solved by updating each of these packages
> `@nestjs/common @nestjs/core @nestjs/platform-express` to `7.4.4`

**Comment by iamelru** [comment]
Still can replicate by following the [Introduction Alternatives](https://docs.nestjs.com/#alternatives) guide.
Cloned the repo and got the same error.

@kamilmysliwiec could you check this, please? Thank you!

**Comment by fabioespinosa** [comment]
I was using node version:
`FROM node:15.2.0-alpine3.10`
changed to
`FROM node:14.16.0-alpine3.10`

and it worked.

**Comment by jamesweb1** [comment]
> I was using node version:
> `FROM node:15.2.0-alpine3.10`
> changed to
> `FROM node:14.16.0-alpine3.10`
> 
> and it worked.

Thanks for your reply, and I face the same issue after upgrading the node to 15.x.x. and I downgrade to the following versions now:

node v14.16.1
nom 6.14.12

It works now.

**Comment by thebarefootdev** [comment]
Fresh install on node 15 and latest libs with apollo etc, still get the same error. Fixed by separately installing @apollo/gateway. I assume then this issue has not yet been fixed?

**Comment by MrrHak** [comment]
I solved my problem by downgrade version of node to v14.16.1 and delete node_modules folder and install it again in my project it worked now.

**Comment by douglas-pires** [comment]
It looks like `@apollo/gateway` is currently unsuportted in node >= 15... They have a plan to update the package when node 16 turns LTS. [Here](https://github.com/apollographql/federation/issues/651) for more info.

However, if you are really into make it work in node version >= 15, and If you are in a controlled environment, you can do `rm -rf node_modules && yarn --ignore-engines`. But again, it's not recommended, but it works if you are, as in my case, doing a side project or something.

**Comment by abernix** [comment]
Seems relevant to share here: As of the landing of apollographql/federation#713, we're now testing `@apollo/gateway` with Node.js 16 and since those tests are passing, the latest versions of the `@apollo/gateway` (`0.28.0`) and `@apollo/federation` (`0.24.0`) packages have just been published with Node.js 16 in their supported `engines` range for `node`.

**Comment by simultsop** [comment]
This issue occurs also with node [16](https://medium.com/the-node-js-collection/node-js-16-available-now-7f5099a97e70)

**Comment by aydearcas** [comment]
Getting this error with node 16 also, gonna try to downgrade to versions 14.6.xxx

**Comment by hantsy** [comment]
Get the same error with NodeJS 16 and the following dependencies.

```json
  "dependencies": {
    "@nestjs/common": "^7.6.15",
    "@nestjs/core": "^7.6.15",
    "@nestjs/graphql": "^7.10.6",
    "@nestjs/platform-express": "^7.6.15",
    "apollo-server": "^2.24.0",
    "apollo-server-express": "^2.24.0",
    "graphql": "^15.5.0",
    "graphql-query-complexity": "^0.8.1",
    "graphql-subscriptions": "^1.2.1",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.0",
    "rxjs": "^6.6.7"
  },
```

**Comment by aydearcas** [comment]
I went back to node LTS (14.17) and it now works as intended!!

**Comment by veritem** [comment]
I'm not sure the reason why you need lts to get rid of this error

**Comment by dlvx** [comment]
I was having this problem while using Node v16.4.2. Problem solved using lts/fermium (v14.17.3)

**Comment by andersonmadeira** [comment]
I fear this issue is not fixed yet, since i'm facing this with what seems to be a up-date version: ^8.0.2
Also my node version should be compatible according to what others said here: v14.16.0
I tried node and yarn, neither worked. :/

**Comment by beyerleinf** [comment]
@andersonmadeira Just encountered the same problem

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/graphql/issues/1621#issuecomment-878199238
